worker_processes 1;
events { worker_connections 1024; }

http {
    include mime.types;
    sendfile on;
    
    server {
        listen 52.41.36.82;
        server_name fast-api.agrehelt-app.great-site.net www.fast-api.agrehelt-app.great-site.net;

        location / {
            proxy_pass https://fast-api-nine-henna.vercel.app/;  # Change this to your Vercel app
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
